### PR TITLE
restart watcher when receive event with nil Object

### LINKED ISSUE #15: ConfigMap Watcher got nil Event
# What's going on?

Injector deployment crash frequently. I got crash log:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xef548b]

goroutine 35 [running]:
github.com/tumblr/k8s-sidecar-injector/internal/pkg/config/watcher.(*K8sConfigMapWatcher).Watch(0xc0002cca00, 0x12d1f60, 0xc0002d8600, 0xc000300600, 0x0, 0x0)
	/src/internal/pkg/config/watcher/watcher.go:109 +0x36b
main.main.func1.1(0xc0002cca00, 0x12d1f60, 0xc0002d8600, 0xc000300600)
	/src/cmd/main.go:114 +0x77
created by main.main.func1
	/src/cmd/main.go:111 +0xd7
```
 I think it just because watcher got a Event with a `nil Object` and try to use it. I find this bug is caused by https://github.com/kubernetes/client-go/issues/334

# Expected Behavior

# Reproducer

can reproduce with any valid sidecar configurations, just wait a few minutes

# Version Deets

* Kubernetes Version: `v1.13.3`
* `k8s-sidecar-injector` Version: `release-v0.1.6`

### PR DESCRIPTION
**Pull request by lxs137**
# What and why?

> Fix #15 
> Be descriptive, give context, and avoid one liners.

# Testing Steps

Please provide adequate testing steps (including screenshots if necessary).
Include any test fixtures or sample configurations in your commit.

- [ ] Added unit tests for this feature (`make test`)

# Reviewers

Required reviewers: `@byxorna`
Request reviews from other people you want to review this PR in the "Reviewers" section on the right.

> :warning: this PR must have at least 2 thumbs from the [MAINTAINERS.md](/MAINTAINERS.md) of the project before merging!

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

File: internal/pkg/config/watcher/watcher.go [hunk 1]
```diff
@@ -106,6 +106,11 @@ func (c *K8sConfigMapWatcher) Watch(ctx context.Context, notifyMe chan<- interfa
 	for {
 		select {
 		case e = <-ch:
+			if e.Object == nil {
+				glog.Errorf("got nil event, restart watcher")
+				watcher.Stop()
+				return nil
```
Comment (byxorna) [inline internal/pkg/config/watcher/watcher.go]: we should return an informative error here, like `fmt.Errorf("watch event object is nil - HTTP connection likely closed")`. It would also be useful to comment that restarting the watcher happens in `cmd/main.go`, and is not performed by anything in `internal/pkg/config/watcher` package.

Additionally, could you drop comments here linking to https://github.com/kubernetes/client-go/issues/334 and explaining the bug this codepath intends to fix?

Comment (lxs137) [reply internal/pkg/config/watcher/watcher.go]: But how to stop watcher in `cmd/main.go`. Add a func `StopWatch` in `internal/pkg/config/watcher`, so `cmd/main.go` can stop watcher?

Comment (byxorna) [reply internal/pkg/config/watcher/watcher.go]: Ah, we should also update https://github.com/tumblr/k8s-sidecar-injector/blob/master/cmd/main.go#L112-L118 so it wont fatal, only log an error. Then, the `for{}` will just call Watch again for us, and everything will be 👌

Comment (lxs137) [reply internal/pkg/config/watcher/watcher.go]: I throw error about this to `cmd/main.go`, I am not sure the watcher will be stopped when function `Watch()` exit.

File: cmd/main.go [hunk 2]
```diff
@@ -113,7 +113,12 @@ func main() {
 				glog.Infof("launching watcher for ConfigMaps")
 				err := configWatcher.Watch(ctx, sigChan)
 				if err != nil {
-					glog.Fatalf("error watching for new ConfigMaps (terminating): %s", err.Error())
+					switch err {
+					case watcher.EventNilObjectError:
+						glog.Errorf("watcher got error, try to restart watcher: %s", err.Error())
```
Comment (byxorna) [inline cmd/main.go]: don't forget to `watcher.Stop()` here, so resources get cleaned up before the next iteration of the `for` loop calls `Watch()` again to restart.

**Comment by lxs137** [comment]
Actually, this bug is caused by HTTP timeout, which related to `--min-request-timeout` option of [kube-apiserver](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/), if set this option to `1800`, watcher will get nil Object every 1800s exactly. 

I found there are two solution to fix this:
* close and recreate the watcher, just like what `informer` do: https://github.com/kubernetes/kubernetes/blob/32b37f5a85e8f2987f8367e611147cd4d4dfa4f9/staging/src/k8s.io/client-go/tools/cache/reflector.go#L319-L340
* use `informer` directly, but this will change other function in `config/watcher`

I want to know which solution do you perfer @byxorna

**Comment by byxorna** [comment]
thanks for digging into this @lxs137 ! I think stopping the watcher when the http connection times out seems like the _easiest_ approach IMO. I like their solution of `defer watcher.Stop()` in `watcher.Watch()` - seems hygienic.

File: internal/pkg/config/watcher/watcher.go [hunk 3]
```diff
@@ -98,14 +102,19 @@ func (c *K8sConfigMapWatcher) Watch(ctx context.Context, notifyMe chan<- interfa
...
 	}
-	ch := watcher.ResultChan()
-	var e watch.Event
 	for {
 		select {
-		case e = <-ch:
+		case e, ok := <-watcher.ResultChan():
+			// channel may closed caused by HTTP timeout, should restart watcher
+			// detail at https://github.com/kubernetes/client-go/issues/334
+			if !ok {
```
Comment (byxorna) [inline internal/pkg/config/watcher/watcher.go]: this is awesome! do you think it would also be useful to catch the following? I noticed the [code you linked](https://github.com/kubernetes/kubernetes/blob/32b37f5a85e8f2987f8367e611147cd4d4dfa4f9/staging/src/k8s.io/client-go/tools/cache/reflector.go#L319-L340) previously also has that.
```
import (
  "k8s.io/apimachinery/pkg/watch"
  apierrs "k8s.io/apimachinery/pkg/api/errors"
)
....
if e.Type == watch.Error {
  return apierrs.FromObject(e.Object)
}
```

Comment (lxs137) [reply internal/pkg/config/watcher/watcher.go]: I think `apierrors.FromObject` just construct specify api-server Error from Object, if we catch that Error, we also should restart watcher.

Comment (byxorna) [reply internal/pkg/config/watcher/watcher.go]: Hmm, I think this type of failure (`e.Type == watch.Error`) should _not_ restart the watcher. This error is not a known condition, and I am not comfortable saying that we know how to remediate it. So, deciding to restart the watcher here is 

IMO, we should add this:
```
if e.Type == watch.Error {
  return apierrs.FromObject(e.Object)
}
```
and have no extra logic to handle this condition in `cmd/main.go`. These errors should be fatal, because we do not know what happened, or how to handle them.

Comment (byxorna) [reply internal/pkg/config/watcher/watcher.go]: Oops, sorry! I didnt realize the latest commit already included this! My bad :)

**Comment by byxorna** [comment]
@lxs137 thank you for this contribution! Awesome work :) I will merge and cut a new release shortly.

Thanks!
